name: app
description: "Proiect realizat de ECHIPA 825 - PIA 2025"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_app_name: ^0.1.0
flutter:
  uses-material-design: true
  fonts:
    - family: Iosevka
      fonts:
        - asset: assets/fonts/IosevkaNerdFont-SemiBold.ttf

flutter_app_name:
  name: "Clock Controller"